#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

downloaddir=/srv/demobuild

mkdir -p ${downloaddir}
pushd ${downloaddir}

yum_excludes=''
for xpackage in nethserver-mail-server nethserver-mail-filter nethserver-mail-common nethserver-getmail nethserver-spamd nethserver-p3scan \
                nethserver-don nethserver-owncloud nethserver-suricata nethserver-webtop4 \
                nethserver-dc nethserver-directory \
                nethserver-ndpi nethserver-lib; do
    yum_excludes="${yum_excludes}-x ${xpackage} "
done
yumdownloader --destdir=. ${yum_excludes} nethserver-\* passwd
curl -O http://packages.nethserver.org/nethserver/6.9/base/x86_64/Packages/nethserver-lib-2.1.5-1.ns6.noarch.rpm

for RPM in *.rpm; do
    echo "[INFO] unpacking ${RPM}"
    rpm2cpio $RPM | cpio -id
done

chown -c -R root:root .
find ${downloaddir} -type d | xargs -- chmod -c 755

mkdir -vp /etc/e-smith/events
mv -v ${downloaddir}/etc/e-smith/events/actions  /etc/e-smith/events
mv -v ${downloaddir}/usr/libexec/nethserver /usr/libexec
mv -v ${downloaddir}/etc/sudoers.d/* /etc/sudoers.d
mv -v ${downloaddir}/sbin/e-smith /usr/sbin
mv -v ${downloaddir}/usr/share/nethesis /usr/share
mv -v ${downloaddir}/usr/share/perl5/vendor_perl/{NethServer,esmith} /usr/share/perl5/vendor_perl
mv -v ${downloaddir}/var/lib/nethserver /var/lib
mv -v ${downloaddir}/var/cache/duc /var/cache
rm -vf ${downloaddir}/etc/httpd/admin-conf.d/rspamd.conf
mv -v ${downloaddir}/etc/httpd/admin-conf.d /etc/httpd

popd

rm -rf ${downloaddir}
rm -rf /var/cache/yum

# Set default root password
PASSWORD="Nethesis,1234"
echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin root

# Disable error reporting:
sed -i "/^ini_set('error_reporting'/ c \
ini_set('error_reporting', 0); \
" /usr/share/nethesis/nethserver-manager/index.php

mkdir -p /etc/httpd/admin-conf{,.d}
mkdir -p /var/cache/nethserver-httpd-admin
mkdir -p /var/log/httpd-admin

chown -c root:root /etc/sudoers.d/*
chmod -c 0440 /etc/sudoers.d/*

sync
